# Numpy

  `**NumPy** (Numerical Python)` is an open source Python library that’s widely used in science and engineering. The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures.

  **Arrays** are a fundamental data structure, and an important part of most programming languages. In Python, they are containers which are able to store more than one item at the same time. Specifically, they are an ordered collection of elements with every value being of the same data type.

# Notes
 0-D (zero-dimensional) array referred to as a `“scalar”`

 1-D array as a `“vector”`  

 2-D (two-dimensional) array as a “**`matrix`**”

 N-dimensional, where “N” is typically an integer greater than 2) array as a **`“tensor”`**  

In [1]:
#import library
import numpy as np
# create List and Array using numpy
#list
List= [1,2,3,4,5,6,7,8,9,10]
# Array
Array=np.array(List)
print(List)
print(Array)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


# Indexing and slicing

In [ ]:
# 1D dimension (vector)
a = np.array([1, 2, 3, 4, 5])

# Accessing elements, same as happens with lists
print(a)        # Prints the entire array
print(a[0])     # Prints the first element
print(a[1])     # Prints the second element
print(a[2])     # Prints the third element
print(a[0:4])   # Prints elements from index 0 to 3 (slicing)
print(a[:3])
print(a[-1])    # Prints the last element
print(a[-3:-1]) # Prints elements from the third last to the second last
print(a[:])     #Print all element array

[1 2 3 4 5]
1
2
3
[1 2 3 4]
[1 2 3]
5
[3 4]
[1 2 3 4 5]


In [10]:
# another method for slicing and indexing
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print("#"*50)
print(a[0])
print("#"*50)
print(a[a < 5])
print(a[a %2 == 0 ])
print("#"*50)
print(a[(a > 2) & (a < 11)])
print("#"*50)
c = a[(a > 2) & (a < 11)]
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
##################################################
[1 2 3 4]
##################################################
[1 2 3 4]
[ 2  4  6  8 10 12]
##################################################
[ 3  4  5  6  7  8  9 10]
##################################################
[ 3  4  5  6  7  8  9 10]


In [ ]:
# 1D dimension (vector)
a = np.array([1, 2, 3, 4, 5])

# Update elements of the array
a[0] = 111  # Update the first element
a[0:3] = [111, 222, 333]  # Update the first three elements

# Print the updated array
print(a)


[111 222 333   4   5]


In [ ]:
#Two- and higher-dimensional arrays can be initialized from nested Python sequences:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
#display array
print(a)
#access elements on multi dimention array
print("#"*50)
print(a[2][2])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
##################################################
11


# Array attributes
This section covers the

       1- ndim ==> will tell you the number of axes, or dimensions, of the array.

       2- size ==> will tell you the total number of elements of the array.

       3- shape ==> will display (n-dimention, num Rows , num columns)
            
       4-dtype
            
                    

In [ ]:
#The number of dimensions ==> ndim

# 1D array
a = np.array([1, 2, 3, 4, 5])

# 2D array
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# 3D array
c = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]]])

# Print the number of dimensions for each array
print(a.ndim)  # Output: 1
print(b.ndim)  # Output: 2
print(c.ndim)  # Output: 3



# The fixed, total number of elements in array is contained in the size attribute.
print(a.size)
print(b.size)
print(c.size)


# The shape of an array
print (a.shape)
print (b.shape)
print (c.shape)



1
2
3
5
8
12
(5,)
(2, 4)
(1, 3, 4)


In [ ]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

print(array_example.ndim)
print(array_example.size)
print(array_example.shape)

3
24
(3, 2, 4)


# How to create a basic array 1-D
np.zeros()

np.ones()

np.empty()

np.arange()

np.linspace()

Specifying your data type     (size of array ,dtype=np.datatype)

In [ ]:
# build array of zeros
Array_zeros= np.zeros(10) # the parameter take the number of elements
print(Array_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# build array of ones
Array_ones = np.ones(10)
#Specifying your data type
Array_int=np.ones(10,dtype=np.int64)
Array_one=np.ones(10,dtype=np.int64)
Array_float =np.ones(10,dtype=np.float64)
print(Array_ones)
print(Array_int)
print(Array_float)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# build array of empty
#The function empty creates an array whose initial content is random and depends on the state of the memory
# The reason to use empty over zeros (or something similar) is speed

Array_empty=np.empty(10)
#Specifying your data type
Array=np.empty(10,dtype=np.int64)

print(Array_empty)
print(Array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[4607182418800017408 4607182418800017408 4607182418800017408
 4607182418800017408 4607182418800017408 4607182418800017408
 4607182418800017408 4607182418800017408 4607182418800017408
 4607182418800017408]


In [ ]:
# create an array with a range of elements:
#(the first number, last number,  the step size)
array_arrange = np.arange(0,10,2)
print(array_arrange)

[0 2 4 6 8]


In [ ]:
#You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:
array_linspace=np.linspace(1,10,num=4)
print(array_linspace)

[ 1.  4.  7. 10.]


# Adding, removing,concatenate and sorting elements
ndarray.sort

Method to sort an array in-place.





  *   argsort


  *  Indirect sort.

  * lexsort

       Indirect stable sort on multiple keys.

  * searchsorted

       Find elements in a sorted array.

  *   partition
  
       Partial sort.

  *   np.concatenate()



In [ ]:
#Sort ASC
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr=np.sort(arr)
print(arr)

[1 2 3 4 5 6 7 8]


In [ ]:
#np.concatenate()

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = np.concatenate((a, b))
print(c)


[1 2 3 4 5 6 7 8]


In [11]:
#create an array from existing data

a1=np.array([1,2,3,4,5,6,7,8,9])
a2=a1[3:8]
print(a2)


[4 5 6 7 8]


In [17]:
#np.vstack() ==> vertically
#np.hstack () ==> horizontally


a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

print(np.vstack((a1, a2)))
print("#"*50)
print(np.hstack((a1, a2)))

[[1 1]
 [2 2]
 [3 3]
 [4 4]]
##################################################
[[1 1 3 3]
 [2 2 4 4]]


# Can you reshape an array?
       arr.reshape() ==> we can conver array from 1d into multiple shapes   And vice versa

In [ ]:
a = np.arange(6)
print(a)
b = a.reshape(3, 2) #array.reshape()
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


# How to convert a 1D array into a 2D array (how to add a new axis to an array)

        1-np.newaxis : np.newaxis is used to increase the dimension of an array by one.  It's primarily used to convert a 1D array into a 2D array (row vector or column vector) or higher-dimensional arrays.
        
        2-np.expan_dims :  np.expand_dims is used to insert a new axis (dimension) into an array. It's similar to np.newaxis, but provides more explicit control.
        

In [2]:
# Example:
a = np.array([1, 2, 3])
print(a.shape)  # Output: (3,) - 1D array

# Adding a new axis to make it a row vector:
row_vector = a[np.newaxis, :]
print(row_vector.shape)  # Output: (1, 3) - 2D array

# Adding a new axis to make it a column vector:
col_vector = a[:, np.newaxis]
print(col_vector.shape)  # Output: (3, 1) - 2D array

# Using None instead of np.newaxis (they are equivalent)
row_vector_none = a[None, :]
print(row_vector_none.shape) #Output: (1,3)
col_vector_none = a[:, None]
print(col_vector_none.shape) #Output: (3,1)



(3,)
(1, 3)
(3, 1)
(1, 3)
(3, 1)


In [3]:
# Example np.expand_dims

a = np.array([1, 2, 3])
print(a.shape)  # Output: (3,)

# Insert a new axis at position 0 (row vector)
b = np.expand_dims(a, axis=0)
print(b.shape)  # Output: (1, 3)

# Insert a new axis at position 1 (column vector)
c = np.expand_dims(a, axis=1)
print(c.shape)  # Output: (3, 1)

# Example with a 2D array
d = np.array([[1, 2], [3, 4]])
print(d.shape)  # (2, 2)

# Insert new axis at position 0
e = np.expand_dims(d, axis=0)
print(e.shape)  # (1, 2, 2)

# Insert new axis at position 1
f = np.expand_dims(d, axis=1)
print(f.shape)  # (2, 1, 2)

(3,)
(1, 3)
(3, 1)
(2, 2)
(1, 2, 2)
(2, 1, 2)


# Basic array operations


> addition , subtraction  ,multiplication  , division


>function sum()


> Broadcasting


  The axis parameter specifies the direction along which the operation is applied:



1.    axis=0: Operates along columns.
2.    axis=1: Operates along rows.










In [23]:
#Basic array operations
arr1 = np.arange(0,20,2)
arr2 = np .arange(0,20,2)
#addition
print(arr1 + arr2)
#multiplication
print(arr1 * arr2)
#subtraction
print(arr1 - arr2)
#division
print(arr1 / arr2)

[ 0  4  8 12 16 20 24 28 32 36]
[  0   4  16  36  64 100 144 196 256 324]
[0 0 0 0 0 0 0 0 0 0]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


<ipython-input-23-d74f9636e1c4>:11: RuntimeWarning: invalid value encountered in divide
  print(arr1 / arr2)


In [25]:
#function sum()
array1=np.array([[1,2,3],[4,5,6]])
print(array1.sum())
print(array1.sum(axis=0))
#note sum(axis=1) ====> [(1+2,+3)    (4+5+6) ]
print(array1.sum(axis=1))



21
[5 7 9]
[ 6 15]


  **Broadcasting**


> operation between a vector and a scalar



> More useful array operations  



* min()
* max ()
* sum()






> get unique items and counts


*   np.unique =  print the unique values in your array:












In [26]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [28]:
#max
print(data.max ())
#min
print(data.min ())
#sum
print(data.sum ())

2.0
1.0
3.0


In [29]:
#another Example
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
#summation all number
print(a.sum())
# The Minimum number in the Matrix
print(a.min())
# The Maximum number in the Matrix
print(a.max())
#The Minimum number at each column
print(a.min(axis=0))
#The Max number at each row
print(a.max(axis=1))


4.8595784
0.05093587
0.82485143
[0.12697628 0.05093587 0.26590556 0.5510652 ]
[0.5510652  0.55645993 0.82485143]


#Generating random numbers

In [32]:
# Generate random numbers from a uniform distribution
uniform_random = np.random.rand(5)  # 5 random numbers between 0 and 1
print("Uniform random numbers:", uniform_random)



# Generate random numbers from a normal distribution (Gaussian)
normal_random = np.random.randn(5)  # 5 random numbers with mean 0 and standard deviation 1
print("Normal random numbers:", normal_random)

# Generate random integers within a range (inclusive of the lower bound, exclusive of the upper bound)
random_integers = np.random.randint(1, 10, size=5)  # 5 random integers between 1 and 9
print("Random integers:", random_integers)

# Generate random numbers from a specific distribution (e.g., exponential)
# exponential_random = np.random.exponential(scale=1.0, size=5) # 5 random numbers from an exponential distribution
# print("Exponential random numbers:", exponential_random)

Uniform random numbers: [0.95060618 0.99042085 0.57974488 0.80759779 0.14058951]
Normal random numbers: [ 0.50815422 -0.53758599  0.46296825  1.19221467  1.47500408]
Random integers: [1 5 1 3 2]


# unique values in your array

In [36]:
#To get the unique rows, index position, and occurrence count
array=np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [7, 8, 9], [1, 2, 3], [4, 5, 6]])
unique_rows, indices, occurrence  = np.unique(array, axis=0, return_counts=True, return_index=True)

print(unique_rows)
print("#"*50)

print(indices)
print("#"*50)

print(occurrence)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
##################################################
[0 1 3]
##################################################
[3 2 1]


In [38]:
#to get unique values at the array
array=np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [7, 8, 9], [1, 2, 3], [4, 5, 6]])
unique_vlaues=np.unique(array)
print(unique_vlaues)

[1 2 3 4 5 6 7 8 9]


In [39]:
unique_values, indices = np.unique(array, return_index=True)
print(unique_values)
print(indices)

[1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  9 10 11]


# Transposing and reshaping a matrix

   {{ convert row into column  And vice versa }}

  arr.reshape()
  
  arr.transpose()
   
  arr.T



In [51]:
array_example = np.array([[0, 1, 2, 3],
                           [4, 5, 6, 7]])
print(array_example)
print("--"*50)
print(array_example.shape)
print("--"*50)
print(array_example.reshape(4,2))






[[0 1 2 3]
 [4 5 6 7]]
----------------------------------------------------------------------------------------------------
(2, 4)
----------------------------------------------------------------------------------------------------
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [46]:
print(array_example.transpose())

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [48]:
print(array_example.T)

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


# How to reverse an array
   
**np.flip(arr)**


In [52]:
# reverse 1-D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print ( reversed_arr)

[8 7 6 5 4 3 2 1]


In [57]:
# reverse 2-D or multiple dimensions  array
arr = np.array([[1, 2, 3, 4, 5, 6, 7, 8],
               [9, 10, 11, 12, 13, 14, 15, 16],
                [17,18,19,20,30,40,50,60]])
reversed_arr = np.flip(arr)
print ( reversed_arr)

[[60 50 40 30 20 19 18 17]
 [16 15 14 13 12 11 10  9]
 [ 8  7  6  5  4  3  2  1]]


# flattening multidimensional arrays


1. arr.flatten() == > make multiple dimensions array as vector 1 column

2.  ravel()




In [82]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
y= x.flatten()
print("old array :\n  ",x,"\n" )

print("\n new array :  " ,  y )

old array :
   [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 


new array :   [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [84]:
# ravel () function
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Flatten the array (creates a copy)
y = x.flatten()
y[0] = 999  # Change the first element of the flattened array

print("Original array (x):\n", x)  # Original array is unchanged
print("\nFlattened array (y):\n", y)

# Ravel the array (creates a view if possible, otherwise a copy)
z = x.ravel()
z[0] = 999  # Change the first element of the raveled array

print("\nOriginal array (x):\n", x)  # Original array is modified (if a view was created)
print("\nRaveled array (z):\n", z)

Original array (x):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flattened array (y):
 [999   2   3   4   5   6   7   8   9  10  11  12]

Original array (x):
 [[999   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

Raveled array (z):
 [999   2   3   4   5   6   7   8   9  10  11  12]


# How to access the docstring for more information



*      help ()
*     ?
*     ??





In [94]:
# docstring help us what this function doing And  what are thire parameters


help(max) # Use np.ravel instead of revel


Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



# Working with mathematical formulas
  

*   LINER Algebra
*   Statistic
* Math for machine learning




In [ ]:
# implementation mean square error (MSE)
error= 1/n * np.sum(np.squared(predictions - labels))

